export const list = [
  {
    name: 'Маргарита Классика',
    menu: 'Традиционная итальянская пицца с томатным соусом, моцареллой и свежим базиликом',
    image: require('../pitsas/margarita.png'),
    count: 1,
  },
  {
    name: 'Пепперони Фестиваль',
    menu: 'Щедро украшенная пицца с пикантными ломтиками пепперони и моцареллой',
    image: require('../pitsas/pepperoni.png'),
    count: 1,
  },
  {
    name: 'Гавайская Гармония',
    menu: 'Пицца с кусочками ветчины и ананаса, идеальное сочетание сладкого и соленого',
    image: require('../pitsas/garmoniya.png'),
    count: 1,
  },
  {
    name: 'Вегетарианский Рай',
    menu: 'Ассорти из свежих овощей: перцев, грибов, оливок и лука на тонкой основе',
    image: require('../pitsas/ray.png'),
    count: 1,
  },
  {
    name: 'Карбонара Крем',
    menu: 'Кремовая пицца с беконом, яйцом и сыром пармезан',
    image: require('../pitsas/karbanaro.png'),
    count: 1,
  },
  {
    name: 'Сицилийская Специя',
    menu: 'Пицца с острым салями, маслинами и каперсами на томатной основе',
    image: require('../pitsas/spetsiya.png'),
    count: 1,
  },
  {
    name: 'Фирменный Фьюжн',
    menu: 'Микс из морепродуктов с соусом альфредо и зеленью',
    image: require('../pitsas/fyujen.png'),
    count: 1,
  },
  {
    name: 'Четыре Сыра',
    menu: 'Сочетание четырех сыров - моцарелла, горгонзола, пармезан и фета',
    image: require('../pitsas/fourcheese.png'),
    count: 1,
  },
  {
    name: 'Лесной Гриб',
    menu: 'Ассорти из дикорастущих грибов с чесночным соусом и моцареллой',
    image: require('../pitsas/margarita.png'),
    count: 1,
  },
  {
    name: 'Мясное Удовольствие',
    menu: 'Говядина, курица, пепперони и бекон с томатным соусом и моцареллой',
    image: require('../pitsas/meat.png'),
    count: 1,
  },
  {
    name: 'Спайси Чили',
    menu: 'Острая пицца с чили, пепперони и луком, для любителей острых ощущений',
    image: require('../pitsas/chili.png'),
    count: 1,
  },
  {
    name: 'Барбекю Царство',
    menu: 'Курица в барбекю соусе, лук и сладкий перец с моцареллой',
    image: require('../pitsas/barbeqque.png'),
    count: 1,
  },
  {
    name: 'Морская Звезда',
    menu: 'Пицца с креветками, мидиями и кальмарами на томатной основе',
    image: require('../pitsas/star.png'),
    count: 1,
  },
  {
    name: 'Тоскана Традиция',
    menu: 'Соус песто, сушеные томаты, артишоки и козий сыр',
    image: require('../pitsas/toskana.png'),
    count: 1,
  },
  {
    name: 'Капризная Дама',
    menu: 'Ветчина, грибы, артишоки и оливки с томатным соусом и моцареллой.',
    image: require('../pitsas/dama.png'),
    count: 1,
  },
  {
    name: 'Осенний Сбор',
    menu: 'Груша, горгонзола, грецкие орехи и мед на тонком тесте',
    image: require('../pitsas/autumn.png'),
    count: 1,
  },
  {
    name: 'Сладкая Фантазия',
    menu: 'Шоколадная пицца с клубникой, бананом и миндалем',
    image: require('../pitsas/fantasy.png'),
    count: 1,
  },
  {
    name: 'Мексиканская Волна',
    menu: 'Говядина, фасоль, кукуруза и острый халапеньо для любителей пикантного',
    image: require('../pitsas/mexico.png'),
    count: 1,
  },
  {
    name: 'Белый Сюрприз',
    menu: 'Белая пицца с рикоттой, моцареллой и чесноком',
    image: require('../pitsas/surprise.png'),
    count: 1,
  },
  {
    name: 'Пикник Пепперони',
    menu: 'Пепперони, моцарелла и помидоры черри на тонкой основе',
    image: require('../pitsas/pikkapepporini.png'),
    count: 1,
  },
  {
    name: 'Альпийский Склон',
    menu: 'Пицца с беконом, картофелем и крем-фреш',
    image: require('../pitsas/apelsin.png'),
    count: 1,
  },
];
